version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
  # Adminer is a SQL database viewer, which can optionally be enabled.
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080